services:
  Richardhj\ContaoAjaxReloadElementBundle\EventListener\AjaxReloadElementListener:
    public: true
    arguments:
      - '@contao.image.picture_factory'
      - '@contao.insert_tag.parser'
  
  Richardhj\ContaoAjaxReloadElementBundle\EventListener\DataContanier\ModifyPalettesListener:
    public: true
